#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

package_upgrade: true

packages:
  - qemu-guest-agent
  - ansible

runcmd:
  - systemctl start qemu-guest-agent
  - systemctl enable qemu-guest-agent
